AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  UseCache: true
  CacheRootDirectory: './'
  Exclude:
    - 'bin/**/*'
    - 'test/files/source.rb' # An example test file for reading source code
    - 'test/minitest/contrived_*' # Intentional failures for testing the reporter

# Let's aim for 80, but we don't need to be nagged if we judiciously go over.
Layout/LineLength:
  Enabled: false

# One case statement in a single method isn't complex. Issue classification
# methods use cascading conditionals that are clear and linear.
Metrics/CyclomaticComplexity:
  AllowedMethods: ['case', 'type', 'issue_label']

# Issue#initialize wraps Minitest::Result with keyword args — all are needed.
# build_issue test helper mirrors those parameters.
Metrics/ParameterLists:
  CountKeywordArgs: false

# Classification and token-building methods are linear with many branches.
# 20 is reasonable for this codebase.
Metrics/AbcSize:
  Max: 20

# Development dependencies in gemspec is fine for this gem
Gemspec/DevelopmentDependencies:
  Enabled: false

# 10 is a good goal but a little draconian
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 15

# Test classes naturally grow with coverage (see test/.rubocop.yml for higher limit)
Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 150

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 150

# Fasterer prefers yield over block.call for performance
Style/ExplicitBlockArgument:
  Enabled: false

# Fasterer prefers fetch with block over second argument for performance
Style/RedundantFetchBlock:
  Enabled: false

# Compact style (Minitest::Heat::IssueTest) is standard for this project.
# Nested style breaks when intermediary names are classes, not modules (e.g. Backtrace).
Style/ClassAndModuleChildren:
  Enabled: false
